- path: lab_manual/course-vm.md
  path_cn: lab_manual_cn/course-vm.md
  reviewed_cn: .github/reviewed/course-vm.md
- path: lab_manual/lab1.md
  path_cn: lab_manual_cn/lab1.md
  reviewed_cn: .github/reviewed/lab1.md
- path: lab_manual/lab2.md
  path_cn: lab_manual_cn/lab2.md
  reviewed_cn: .github/reviewed/lab2.md
- path: lab_manual/lab3.md
  path_cn: lab_manual_cn/lab3.md
  reviewed_cn: .github/reviewed/lab3.md
- path: lab_manual/lab4.md
  path_cn: lab_manual_cn/lab4.md
  reviewed_cn: .github/reviewed/lab4.md
- path: lab_manual/lab5.md
  path_cn: lab_manual_cn/lab5.md
  reviewed_cn: .github/reviewed/lab5.md
- path: lab_manual/lab6.md
  path_cn: lab_manual_cn/lab6.md
  reviewed_cn: .github/reviewed/lab6.md
- path: lab_manual/lab7.md
  path_cn: lab_manual_cn/lab7.md
  reviewed_cn: .github/reviewed/lab7.md
- path: lab_manual/lab8.md
  path_cn: lab_manual_cn/lab8.md
  reviewed_cn: .github/reviewed/lab8.md
- path: lab_manual/lab9-MiniCREST.md
  path_cn: lab_manual_cn/lab9-MiniCREST.md
  reviewed_cn: .github/reviewed/lab9-MiniCREST.md
- path: lab_manual/lab9.md
  path_cn: lab_manual_cn/lab9.md
  reviewed_cn: .github/reviewed/lab9.md